modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Global slab support through named, legal Slabbed state grammar.
'''

[[mixins]]
config="slabbed.mixins.json"

[[mixins]]
config="slabbed.client.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="fabric_api"
type="required"
versionRange="[0.116.7,)"
ordering="AFTER"
side="BOTH"
